import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

const LOG_PREFIX = '[@crudadmin/helpers]';

/**
 * Pull the gettext catalog of one language from the backend.
 *
 * The bootstrap endpoint answers in the language of the app-locale header and
 * carries the whole catalog, which is the same one the running site
 * translates with. Route paths are ordinary msgids in it.
 */
const fetchCatalog = async (url, locale) => {
    const response = await fetch(url, {
        headers: { 'app-locale': locale },
    });

    if (response.ok === false) {
        throw new Error(`${url} answered ${response.status}`);
    }

    const payload = await response.json();

    let catalog = payload?.store?.locale?.translations;

    if (typeof catalog === 'string') {
        catalog = JSON.parse(catalog);
    }

    const messages = catalog?.messages?.[''] || {};
    const translations = {};

    Object.keys(messages).forEach((msgid) => {
        const translated = [].concat(messages[msgid])[0];

        // An empty entry means the translator has not filled it in yet.
        if (translated && translated !== msgid) {
            translations[msgid] = translated;
        }
    });

    return translations;
};

/**
 * Catalogs of every language, keyed by language slug.
 *
 * A build must not depend on the backend being up, so a failed fetch falls
 * back to the cache written by the last successful one.
 */
export const fetchRouteTranslations = async (options) => {
    const { locales = [], apiUrl, bootstrapPath, cacheFile } = options;

    if (!apiUrl) {
        // prettier-ignore
        console.warn(`${LOG_PREFIX} translateRoutes is on but no apiUrl was resolved. Set localization.apiUrl or VITE_APP_SERVER_URL.`);

        return readTranslationCache(cacheFile);
    }

    const url = String(apiUrl).replace(/\/+$/, '') + bootstrapPath;
    const translations = {};

    try {
        for (const locale of locales) {
            translations[locale] = await fetchCatalog(url, locale);
        }
    } catch (e) {
        // prettier-ignore
        console.warn(`${LOG_PREFIX} could not read route translations from ${url} (${e.message}). Falling back to ${cacheFile || 'no cache'}.`);

        return readTranslationCache(cacheFile);
    }

    return translations;
};

/**
 * Translations of the last successful build, so an unreachable backend does
 * not silently strip every translated path from the site.
 */
export const readTranslationCache = (file) => {
    if (!file || existsSync(file) === false) {
        return {};
    }

    try {
        return JSON.parse(readFileSync(file, 'utf-8')) || {};
    } catch (e) {
        return {};
    }
};

/**
 * Reduce a catalog to the paths that are actually routes.
 *
 * Nothing else is of any use here, and it keeps the cache small and readable
 * enough to be committed.
 */
export const filterRouteTranslations = (translations, paths) => {
    const filtered = {};

    Object.keys(translations || {}).forEach((locale) => {
        const source = translations[locale] || {};
        const kept = {};

        paths.forEach((path) => {
            if (source[path]) {
                kept[path] = source[path];
            }
        });

        filtered[locale] = kept;
    });

    return filtered;
};

/**
 * How many translated paths a catalog holds, across all languages.
 */
export const countTranslations = (translations) => {
    return Object.values(translations || {}).reduce(
        (total, locale) => total + Object.keys(locale || {}).length,
        0
    );
};

/**
 * Remember the paths of this build for the next one.
 */
export const writeTranslationCache = (file, translations) => {
    if (!file) {
        return;
    }

    writeFile(file, JSON.stringify(translations, null, 4) + '\n');
};

/**
 * Write the route paths out as gettext calls.
 *
 * Nothing imports this file. It exists so the CrudAdmin gettext scanner, which
 * reads the paths in admin.gettext.source_paths, finds the route paths and
 * offers them for translation in the administration.
 */
export const writeGettextSource = (file, paths) => {
    if (!file) {
        return;
    }

    const calls = paths
        .map((path) => `    __(${JSON.stringify(path)}),`)
        .join('\n');

    writeFile(
        file,
        [
            '// Generated by @crudadmin/helpers. Do not edit.',
            '//',
            '// Route paths listed as gettext calls, so the CrudAdmin scanner picks',
            '// them up and they can be translated in the administration. Translating',
            '// one changes the url of that page on the next build.',
            'export default [',
            calls,
            '];',
            '',
        ].join('\n')
    );
};

const writeFile = (file, content) => {
    const directory = dirname(file);

    if (existsSync(directory) === false) {
        mkdirSync(directory, { recursive: true });
    }

    // Do not touch the file when nothing changed, a rewrite would retrigger
    // the dev server watcher on every pages:extend pass.
    if (existsSync(file) && readFileSync(file, 'utf-8') === content) {
        return;
    }

    writeFileSync(file, content);
};
